// <auto-generated />
using Blazor_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_API.Migrations
{
    [DbContext(typeof(DietaContext2))]
    partial class DietaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Alimentos", b =>
                {
                    b.Property<int>("AlimentosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlimentosId"));

                    b.Property<string>("Alimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Carboidrato")
                        .HasColumnType("float");

                    b.Property<int>("DietaId")
                        .HasColumnType("int");

                    b.Property<double>("Fibra")
                        .HasColumnType("float");

                    b.Property<double>("Kcal")
                        .HasColumnType("float");

                    b.Property<double>("Lipidio")
                        .HasColumnType("float");

                    b.Property<string>("Preparo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Proteina")
                        .HasColumnType("float");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.HasKey("AlimentosId");

                    b.HasIndex("DietaId");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<int>("DietaId")
                        .HasColumnType("int");

                    b.Property<double>("GastoMetaBasal")
                        .HasColumnType("float");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<int>("TreinoFreq")
                        .HasColumnType("int");

                    b.Property<string>("informacaoAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoDieta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Dieta", b =>
                {
                    b.Property<int>("DietaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.HasKey("DietaId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Dietas");
                });

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Alimentos", b =>
                {
                    b.HasOne("Blazor_MestreDetalhes.Data.Dieta", "Dieta")
                        .WithMany("Refeicao1")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Dieta", b =>
                {
                    b.HasOne("Blazor_MestreDetalhes.Data.Cliente", "Cliente")
                        .WithOne("Dieta")
                        .HasForeignKey("Blazor_MestreDetalhes.Data.Dieta", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Cliente", b =>
                {
                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("Blazor_MestreDetalhes.Data.Dieta", b =>
                {
                    b.Navigation("Refeicao1");
                });
#pragma warning restore 612, 618
        }
    }
}
